# Generated by Django 2.2.1 on 2019-05-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_account_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
