# Generated by Django 2.2.1 on 2019-05-18 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votingcontent', models.CharField(max_length=30, verbose_name='投票内容')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OptionNo1', models.CharField(max_length=30, verbose_name='选项一')),
                ('OptionNo2', models.CharField(max_length=30, verbose_name='选项二')),
                ('Poll_1', models.IntegerField(verbose_name='选项一的票数')),
                ('Poll_2', models.IntegerField(verbose_name='选项二的票数')),
                ('vo_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.VoteContent', verbose_name='投票名')),
            ],
        ),
    ]
