# Generated by Django 2.2.1 on 2019-05-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='标题的图片')),
                ('desc', models.CharField(max_length=20, verbose_name='图片的介绍')),
            ],
            options={
                'verbose_name': '首页第一个图片内容',
                'verbose_name_plural': '首页第一个图片内容',
            },
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标签')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': '介绍公司',
                'verbose_name_plural': '介绍公司',
            },
        ),
        migrations.CreateModel(
            name='CateGory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50, verbose_name='地址')),
                ('phone', models.CharField(max_length=50, verbose_name='电话')),
                ('emsil', models.CharField(max_length=50, verbose_name='邮箱')),
                ('url', models.CharField(max_length=50, verbose_name='网站')),
                ('body', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '联系我们',
                'verbose_name_plural': '联系我们',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('introduce', models.TextField(verbose_name='简介')),
                ('post', models.CharField(max_length=50, verbose_name='岗位')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20, verbose_name='图片的标题')),
            ],
            options={
                'verbose_name': '图片的标题',
                'verbose_name_plural': '图片的标题',
            },
        ),
        migrations.CreateModel(
            name='Staffimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staimg', models.ImageField(upload_to='staff', verbose_name='员工头像')),
                ('staimg_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Staff')),
            ],
            options={
                'verbose_name': '员工头像',
                'verbose_name_plural': '员工头像',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='标题的图片')),
                ('img_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Title')),
            ],
            options={
                'verbose_name': '投资组合图片',
                'verbose_name_plural': '投资组合图片',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('creat_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.CateGory')),
                ('tags', models.ManyToManyField(to='server.Tag')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
