# Generated by Django 2.2.1 on 2019-05-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='标题的图片')),
                ('desc', models.CharField(max_length=20, verbose_name='图片的介绍')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': '联系我们', 'verbose_name_plural': '联系我们'},
        ),
    ]
