# Generated by Django 2.2.1 on 2019-05-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190529_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': '首页第一个图片内容', 'verbose_name_plural': '首页第一个图片内容'},
        ),
    ]
