# Generated by Django 2.2.1 on 2019-05-29 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20190529_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20, verbose_name='图片的标题')),
            ],
            options={
                'verbose_name': '图片的标题',
                'verbose_name_plural': '图片的标题',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='标题的图片')),
                ('img_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Title', verbose_name='标题id')),
            ],
            options={
                'verbose_name': '投资组合图片',
                'verbose_name_plural': '投资组合图片',
            },
        ),
    ]
