# Generated by Django 2.2.1 on 2019-05-29 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_picture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Title'),
        ),
    ]
