# Generated by Django 2.2.1 on 2019-05-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Poll_1',
            field=models.IntegerField(null=True, verbose_name='选项一的票数'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Poll_2',
            field=models.IntegerField(null=True, verbose_name='选项二的票数'),
        ),
    ]
