# Generated by Django 2.2.1 on 2019-05-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20190518_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Poll_1',
            field=models.IntegerField(max_length=50, null=True, verbose_name='选项一的票数'),
        ),
    ]
